### ISSUE TITLE
Help option should not generate an 'az cli' error on api sub-groups

### ISSUE THREAD

**Issue by sjoubert** [Cosmo-Tech/Babylon#13]
When calling `babylon api [solution|organization] --help`, I get the following error:
```
$ babylon api organization --help
AzureCliCredential.get_token failed: ERROR: argument --resource: expected one argument

Examples from AI knowledge base:
az account get-access-token
Get an access token for the current account

az account get-access-token --subscription 00000000-0000-0000-0000-000000000000
Get an access token for a specific subscription

https://docs.microsoft.com/en-US/cli/azure/account#az_account_get_access_token
Read more about the command in reference docs

Traceback (most recent call last):
  File "[...]/babylon/.venv/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 141, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource ']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/bin/babylon", line 33, in <module>
    sys.exit(load_entry_point('Babylon', 'console_scripts', 'babylon')())
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "[...]babylon/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/babylon/Babylon/utils/decorators.py", line 152, in wrapper
    func(*args, **kwargs)
  File "[...]/babylon/Babylon/utils/decorators.py", line 152, in wrapper
    func(*args, **kwargs)
  File "[...]/babylon/Babylon/groups/api/__init__.py", line 24, in api
    token = credentials.get_token(api_scope)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 73, in get_token
    output = _run_command(command)
  File "[...]/babylon/.venv/lib/python3.10/site-packages/azure/identity/_credentials/azure_cli.py", line 154, in _run_command
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: ERROR: argument --resource: expected one argument

Examples from AI knowledge base:
az account get-access-token
Get an access token for the current account

az account get-access-token --subscription 00000000-0000-0000-0000-000000000000
Get an access token for a specific subscription

https://docs.microsoft.com/en-US/cli/azure/account#az_account_get_access_token
Read more about the command in reference docs
```
Ideally consulting the `--help` option should not require a valid Azure config/setup, or at least not trigger an error.

**Comment by neomatamune** [comment]
Would need a bigger dive down in Click to find how we could check for the existence of a future "--help"

The following issue exists in click but was closed, could help to start looking there.
https://github.com/pallets/click/issues/295
